### ISSUE TITLE
Minium doesn't start automatically

### ISSUE THREAD

**Issue by prototyp3** [viltgroup/minium-tools#1]
While I was trying to start minium it threw an exception and didn't open the browser window. Even so, I was able to start by manually typing the url in the browser

<pre>
Exception in thread "main" java.lang.UnsupportedOperationException: Desktop API is not supported on the current platform
	at java.awt.Desktop.getDesktop(Desktop.java:144)
	at minium.developer.browser.BrowserLauncher.launch(BrowserLauncher.java:31)
	at minium.developer.Application.maybeLaunchBrowser(Application.java:103)
	at minium.developer.Application.main(Application.java:88)
</pre>

My system: Arch Linux 64 + XFCE + Google Chrome + Firefox

**Comment by prototyp3** [comment]
Seems to be a Java integration with Linux problem!

from oracle: http://bugs.java.com/bugdatabase/view_bug.do?bug_id=6486393
